### PR TITLE
Help needed!

### PR DESCRIPTION
**Pull request by marschallphilipp**
Hey folks, is there any way to get help on this integration?
Are the Github Issues deactivated?

I am trying to figure out how I can add more sensors to the integration in order to use them for the Energy Dashboard in HA.

I´m trying to add daily sensors for EVU, Battery etc. but don´t see any value in HA.
I added some sensors (#own) in const.py:
image

After enabling them within the integration settings I can see them but they don´t show the right value:
image

Any way to get help?
Thanks!

### CODE REVIEW

**Comment by ChristophCaina** [comment]
Hi,
I've had a look into your changes, and they are pretty much the same as I did in my changes.
Unfortunately, I don't have a battery setup - so I can't really test these, but have you checked what the topic will provide when you use MQTT explorer?

**Comment by ChristophCaina** [comment]
I don't have a battery in use - and therefore, I can't really help with that - but have you checked what output will be shown when for that topic when you use MQTT explorer?

Also, please make sure, that DailyYieldXXX is a total increasing sensor... if this sensor only provides the daily import and export, it should reset at the end of the day (in this case, it's not total_increasing - and not really usefull for the energy dashboard)

**Comment by marschallphilipp** [comment]
Thanks, @ChristophCaina !
I think my problem is not really related to battery, I also tried to add evu sensors for daily usage:
image
Although values below are missing the leading 0,XXXX, I can see reasonable values in MQTT Explorer for all sensors I would like to add to the integration:
image

I found an issue which makes me hoping to see the daily sensors in version v0.5 :-)
https://github.com/ChristophCaina/openwbmqtt/issues/14
Thanks!

**Comment by ChristophCaina** [comment]
Hi,
Can you please try the files from this branch?
https://github.com/ChristophCaina/openwbmqtt/tree/14-add-sensors

**Pull request closed without merging**
